### ISSUE TITLE
first seen date incorrect

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/chainquery#100]
Looking through the rich list, first seen date is incorrect sometimes. 
```
26 | bWSMffekweo6ugrKhgY1aHiszQqycj3kfs | 1,026,431.63660000 | $20,528.63 | 01 Jan 1970 00:00:00 UTC | 0.18717%

```

**Comment by tiger5226** [comment]
We can create a sync method to set these values correctly for older data.

**Comment by tiger5226** [comment]
closing in favor of https://github.com/lbryio/chainquery/issues/103
