### ISSUE TITLE
Migrate Baremetal Chainquery db to production

### ISSUE THREAD

**Issue by tiger5226** [lbryio/chainquery#103]
This is for a full resync of Chainquery database. It will fix older data issues that we see. Please attach fixed issues that are good going forward but need a resync for old data.

**Comment by jessopb** [comment]
Test after resync: https://spee.ch/@NRR:97db3b6c7444a8a4c95cca3611ce88c85d3cfcbd
Chainquery has no claims with publisher_id = 97db3b6c7444a8a4c95cca3611ce88c85d3cfcbd

**Comment by tzarebczan** [comment]
test after resync: https://explorer.lbry.io/tx/de23687d057583d33a44f8e39803bbebd4c313050d50d1e5753e887226b0b818 - check link to spent, right now it goes to https://explorer.lbry.io/tx/#input-

**Comment by nikooo777** [comment]
It's done, and the above now works i believe
