### ISSUE TITLE
Add support for trending receipts per address / claim

### ISSUE THREAD

**Issue by kauffj** [lbryio/chainquery#106]
Take the same logic being used to calculate view trending in our internal logic (Z scores, etc.) and apply it to LBC received by addresses / claims.

This allows for the detection of trending channels and claims on a support/tip/payment basis.

I think it is debatable that this is appropriate to add to chainquery since it is not pure blockchain data. Let's discuss whether this is appropriate either on the ticket or in chat.

**Comment by tiger5226** [comment]
I think it is applicable. We do this in other areas too, namely metadata. This is technically just a set of bytes but we transform it into columns for usability. We already have a supports table too so it should not be too difficult if this is what we end up doing.

**Comment by kauffj** [comment]
Some additional clarification what this should be able to support:

- Fetching trending content across a variety of fixed time windows (e.g. 1 hour, 24 hours, 1 week, 1 month, 1 year)
- Restricting the above by tag (matches one tag or matches at least one tag in a set)
- Restricting the above by publish date (show me trending content over the last week but only among things that were published within the last week)

**Comment by lyoshenka** [comment]
This is happening in https://github.com/lbryio/lbry/pull/2008

**Comment by tiger5226** [comment]
@lyoshenka  I just noticed this, just to be clear trending will instead happen in the wallet server?

**Comment by lyoshenka** [comment]
No this is me being stupid.

**Comment by lyoshenka** [comment]
yes
