### ISSUE TITLE
Height is 0 on ~175K claims

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/chainquery#107]
https://traction.lbry.io/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo2LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjI5OCwiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkLWlkIiw3Mzg3XSwwXV0sImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdXX19LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=

We have tx and timestamp, probably just a data bug somewhere. Block has the correct height

**Comment by tiger5226** [comment]
This is solved with recent patch release.
