### ISSUE TITLE
Spent bid state is being changed since 1.8 release

### ISSUE THREAD

**Issue by tiger5226** [lbryio/chainquery#117]
If you run this query

```sql
SELECT COUNT(*) FROM claim 
 INNER JOIN output ON output.vout = claim.vout AND output.transaction_hash = claim.transaction_hash_id
 WHERE output.is_spent
 AND claim.bid_state != "Spent"
```
It should return 0 but it wasn't. There were 4K claims that needed to be fixed. I fixed them but I need to see what changed that's causing this regression issue. 

Originally reported by EF on discord.
```sql
SELECT bid_state,modified_at FROM chainquery.claim WHERE name = "monty-hall"
```

**Comment by tzarebczan** [comment]
I think this bug is back now that we re-synced.

**Comment by tzarebczan** [comment]
Finding some more claims that are abandoned, but not marked as such in CQ. This causes some issues on the app side similar to the recent LH issue returning invalid claim names. 

The others:  
7da23b53cd93f6378e3efc1bfaeb57a7cdbd03bb / 385ecab5c3e1a64f09af43b3aedc4e28776d947e and many more from publisher: 3abdb253b170f5843a5123dbe7ffdb2c88f9479c

**Comment by tiger5226** [comment]
I found the bug for this. We had added a new column to output (`claim_id`) and it was not being set but it was used in the query where we select claims that need to be marked abandoned. Therefore no claims were being marked abandoned. fixed with https://github.com/lbryio/chainquery/pull/134
