### ISSUE TITLE
Initializing LBRYcrd Client: -32601: getinfo

### ISSUE THREAD

**Issue by AlessandroSpallina** [lbryio/chainquery#121]
I'm unsuccessfully trying to start chainquery for the first time. 
Both from the binary distributed as release and from source I have the following error: https://arin.ga/Quedz7

I suppose the problem is related to btcsuite/btcd/rpcclient dependency (https://arin.ga/1a9ghZ), since version 0.16 in lbrycrd the command "getinfo" (in favor of "-getinfo") has been deprecated and this modification has not been propagated to dependency

**Comment by tzarebczan** [comment]
@tiger5226 can you take a look? Probably just need to use one of the new status commands.

**Comment by tiger5226** [comment]
what version of lbrycrd are you using?

chainquery only supports up to 0.12.4
working on a release for 17 (edited) 
it appears you are using version 17 but I could be wrong.
specifically the go client for lbrycrd has issues with the upstream merge with bitcoin. I have resolved most of them but have a few more kinks to work out before I can release

**Comment by AlessandroSpallina** [comment]
* LBRYcrd Core Daemon version v0.17.2.1-05381f2
* Chainquery Semantic Version:  v1.8.1
* go version go1.12.7 linux/amd64
* ubuntu 18.04

**Comment by AlessandroSpallina** [comment]
Thx for the answer @tiger5226, do you have any timing info for the fix?

**Comment by tiger5226** [comment]
I am working through some important ytsync work to get youtubers their channels to manage them themselves. Once that is complete, I will be back to this. I expect to be back to it in a week or so.

**Comment by AlessandroSpallina** [comment]
Good, in the meanwhile I found a combo that works:
LBRYcrd v0.12.4.1
LBRY Chainquery v1.8.1

**Comment by tiger5226** [comment]
release 1.9.0 fixes this.
