### ISSUE TITLE
Debug chainquery sync process

### ISSUE THREAD

**Issue by kauffj** [lbryio/chainquery#132]
Spinning up a new chainquery instance encounters failures with too high of frequency. Changes to be determined.

**Comment by tiger5226** [comment]
@nikooo777 if this is not resolved now, let me know specific examples please, otherwise I will close this issue.

**Comment by nikooo777** [comment]
Roger I'll attempt to resync the whole chain from scratch again to see if it works fine

**Comment by tiger5226** [comment]
Awesome, if you are going to resync, use master too. I put a bunch of fixes there that would be good to test. I am working on the multi-level concurrency too. Depending on when you get to this, maybe we can test drive it as part of the resync.

**Comment by tiger5226** [comment]
@nikooo777 I pushed the fix for the certificate sync.

**Comment by tiger5226** [comment]
Closing this.
