### ISSUE TITLE
Address table should not use a serial id

### ISSUE THREAD

**Issue by tiger5226** [lbryio/chainquery#16]
The address table should just leverage the address column as its primary key. No sense in having an id column too. This is only useful when there are multiple parts to the primary for the orm. 

This also simplifies queries involving transaction addresses.

**Comment by tiger5226** [comment]
Serial IDs are pretty standard. Also this was created before I figured out the required joins.

**Comment by kauffj** [comment]
I think @lyoshenka and I are both pro surrogate keys.

**Comment by lyoshenka** [comment]
in general, yes. in this case, no. its kind of dumb for an address to store a transaction_id when it could just be storing the transaction hash.

on the other hand, the hashes take up a lot of space, so maybe ids are more space-efficient
