### ISSUE TITLE
Concurrent write to map in lbryschema.go

### ISSUE THREAD

**Issue by roylee17** [lbryio/chainquery#23]
INFO[2018-05-15T03:55:32-07:00] running iteration at block height 177700 16 go routines
INFO[2018-05-15T03:55:38-07:00] running iteration at block height 177750 23 go routines
INFO[2018-05-15T03:55:45-07:00] running iteration at block height 177800 16 go routines
INFO[2018-05-15T03:55:52-07:00] running iteration at block height 177850 16 go routines
INFO[2018-05-15T03:55:59-07:00] running iteration at block height 177900 23 go routines
INFO[2018-05-15T03:56:05-07:00] running iteration at block height 177950 16 go routines
fatal error: concurrent map writes

goroutine 84726677 [running]:
runtime.throw(0x1776380, 0x15)
	/usr/local/Cellar/go/1.10.2/libexec/src/runtime/panic.go:616 +0x81 fp=0xc42091ae30 sp=0xc42091ae10 pc=0x102b4c1
runtime.mapassign_faststr(0x16a4140, 0xc4202521b0, 0x17715b5, 0xf, 0xc4203b0268)
	/usr/local/Cellar/go/1.10.2/libexec/src/runtime/hashmap_fast.go:779 +0x3ce fp=0xc42091aea0 sp=0xc42091ae30 pc=0x100d6de
github.com/lbryio/chainquery/vendor/github.com/lbryio/lbryschema.go/address.SetPrefixes(...)
	/Users/roylee17/go/src/github.com/lbryio/chainquery/vendor/github.com/lbryio/lbryschema.go/address/validate.go:27
github.com/lbryio/chainquery/vendor/github.com/lbryio/lbryschema.go/address.PrefixIsValid(0x918ed0050a040955, 0x5558f36b16e46147, 0x7478b5cc639f2e0b, 0xc4200bc985, 0x176f65b, 0xc, 0x1cb1330)
	/Users/roylee17/go/src/github.com/lbryio/chainquery/vendor/github.com/lbryio/lbryschema.go/address/validate.go:32 +0xac fp=0xc42091aee8 sp=0xc42091aea0 pc=0x154d5dc
github.com/lbryio/chainquery/vendor/github.com/lbryio/lbryschema.go/address.ValidateAddress(0x918ed0050a040955, 0x5558f36b16e46147, 0x7478b5cc639f2e0b, 0xc420c74b85, 0x176f65b, 0xc, 0x0, 0x0, 0x0, 0x191bb00, ...)
	/Users/roylee17/go/src/github.com/lbryio/chainquery/vendor/github.com/lbryio/lbryschema.go/address/validate.go:59 +0x12b fp=0xc42091af30 sp=0xc42091aee8 pc=0x154d84b
github.com/lbryio/chainquery/vendor/github.com/lbryio/lbryschema.go/address.EncodeAddress(0x918ed0050a040955, 0x5558f36b16e46147, 0x7478b5cc639f2e0b, 0x1915485, 0x176f65b, 0xc, 0x0, 0x1915400, 0xc42091b060, 0x150cc27)
	/Users/roylee17/go/src/github.com/lbryio/chainquery/vendor/github.com/lbryio/lbryschema.go/address/encode.go:8 +0x67 fp=0xc42091afd8 sp=0xc42091af30 pc=0x154d467
github.com/lbryio/chainquery/vendor/github.com/lbryio/lbryschema.go/claim.(*ClaimHelper).ValidateAddresses(0xc420452020, 0x176f65b, 0xc, 0x1915400, 0xc420524540)
	/Users/roylee17/go/src/github.com/lbryio/chainquery/vendor/github.com/lbryio/lbryschema.go/claim/claim.go:29 +0xee fp=0xc42091b070 sp=0xc42091afd8 pc=0x15551ae
github.com/lbryio/chainquery/vendor/github.com/lbryio/lbryschema.go/claim.(*ClaimHelper).LoadFromBytes(0xc420452020, 0xc42080ac13, 0x520, 0xbed, 0x176f65b, 0xc, 0xc42039c460, 0x100000000000020)
	/Users/roylee17/go/src/github.com/lbryio/chainquery/vendor/github.com/lbryio/lbryschema.go/claim/claim.go:68 +0x143 fp=0xc42091b0c0 sp=0xc42091b070 pc=0x15555f3
github.com/lbryio/chainquery/vendor/github.com/lbryio/lbryschema.go/claim.DecodeClaimBytes(0xc42080ac13, 0x520, 0xbed, 0x176f65b, 0xc, 0xc420c38000, 0x0, 0x1e25b20)
	/Users/roylee17/go/src/github.com/lbryio/chainquery/vendor/github.com/lbryio/lbryschema.go/claim/claim.go:90 +0xa1 fp=0xc42091b118 sp=0xc42091b0c0 pc=0x1555881
github.com/lbryio/chainquery/daemon/processing.decodeClaimFromValueBytes(0xc42080ac13, 0x520, 0xbed, 0x28, 0xc42033e210, 0x10000c420f971f0)
	/Users/roylee17/go/src/github.com/lbryio/chainquery/daemon/processing/value.go:54 +0x58 fp=0xc42091b168 sp=0xc42091b118 pc=0x155efa8
github.com/lbryio/chainquery/daemon/processing.DecodeClaimValue(0xc420564430, 0xe, 0xc42080ac13, 0x520, 0xbed, 0xc42080ac13, 0x520, 0xbed)
	/Users/roylee17/go/src/github.com/lbryio/chainquery/daemon/processing/value.go:17 +0x5d fp=0xc42091b290 sp=0xc42091b168 pc=0x155eaad
github.com/lbryio/chainquery/daemon/processing.processClaimNameScript(0xc420f978f0, 0x376cb4, 0x19b615, 0xc42038e500, 0x40, 0x3f847ae147ae147b, 0x1, 0x0, 0xc4209eccc0, 0xb, ...)
	/Users/roylee17/go/src/github.com/lbryio/chainquery/daemon/processing/claim.go:58 +0x20b fp=0xc42091b5c0 sp=0xc42091b290 pc=0x155944b
github.com/lbryio/chainquery/daemon/processing.processAsClaim(0xc42080ac00, 0x54e, 0xc00, 0x376cb4, 0x19b615, 0xc42038e500, 0x40, 0x3f847ae147ae147b, 0x1, 0x0, ...)
	/Users/roylee17/go/src/github.com/lbryio/chainquery/daemon/processing/claim.go:24 +0x634 fp=0xc42091b8f0 sp=0xc42091b5c0 pc=0x1559174
github.com/lbryio/chainquery/daemon/processing.processScriptForClaim(0x376cb4, 0x19b615, 0xc42038e500, 0x40, 0x3f847ae147ae147b, 0x1, 0x0, 0xc4209eccc0, 0xb, 0x1, ...)
	/Users/roylee17/go/src/github.com/lbryio/chainquery/daemon/processing/outpoint.go:249 +0x1bf fp=0xc42091bb60 sp=0xc42091b8f0 pc=0x155d6df
github.com/lbryio/chainquery/daemon/processing.processVout(0xc42030c540, 0xc420142780, 0xc420e56040, 0x0, 0x0)
	/Users/roylee17/go/src/github.com/lbryio/chainquery/daemon/processing/outpoint.go:210 +0x3e2 fp=0xc42091bf70 sp=0xc42091bb60 pc=0x155cf92
github.com/lbryio/chainquery/daemon/processing.voutProcessor(0xc42013e1e0, 0xc42013e2a0)
	/Users/roylee17/go/src/github.com/lbryio/chainquery/daemon/processing/outpoint.go:48 +0x67 fp=0xc42091bfd0 sp=0xc42091bf70 pc=0x155bb97
runtime.goexit()
	/usr/local/Cellar/go/1.10.2/libexec/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42091bfd8 sp=0xc42091bfd0 pc=0x10566c1
created by github.com/lbryio/chainquery/daemon/processing.initVoutWorkers
	/Users/roylee17/go/src/github.com/lbryio/chainquery/daemon/processing/outpoint.go:42 +0x52

**Comment by roylee17** [comment]
Quick (less instrumental) fix at lbryio/lbryschema.go#2

Will need to update *dep* revision for *lbryschema.go*

**Comment by tiger5226** [comment]
Interesting, never ran into that with all the sync's I have done! How many cores were running it with if you don't mind me asking?

**Comment by roylee17** [comment]
Guess I was the lucky one.

I'm running it on my 8-core MacBook Pro.

**Comment by tiger5226** [comment]
I run it on my macbook pro too, but `MacBookPro14,2` so only two cores. More chances for you to find concurrency issues. Thanks for reporting this and fixing it too! Let me see if I can get you some credits. All contributions are appreciated!
