### ISSUE TITLE
Recovery from 'ClaimTrieSync: unable to sync claim'?

### ISSUE THREAD

**Issue by roylee17** [lbryio/chainquery#24]
Is there a recovery instruction from the *ClaimTrieSync: unable to sync claim* error?

![screen shot 2018-05-15 at 10 32 55 am](https://user-images.githubusercontent.com/97372/40073548-fbf4ecf0-582b-11e8-89d0-365a1e558a48.png)

**Comment by tiger5226** [comment]
Yes I ran into this today with the sync on dev. It is a problem with a few fields not being large enough. I fixed the database in production and locally but I need to create a migration for it. I can get fixed for you tonight if you need it urgently.

**Comment by roylee17** [comment]
No worries. I'm re-syncing now.
Reading the paper in the mean time. 
Thanks.

**Comment by tiger5226** [comment]
a quick fix for the problem above is to make the decimal columns DECIMAL(50,8). Ultimately, I will also have a migration to fix that as they should not be decimal they should be integers.

**Comment by tiger5226** [comment]
accidentally closed. We need a migration so from scratch startup works seamlessly.

**Comment by tiger5226** [comment]
added migration for `effective_amount` and `fee` on table `claim` to resolve this sync claim issue. 

f81d9ead05355f290d1fbed0a8a1fb4af68cc954
