### ISSUE TITLE
Claim is missing channel

### ISSUE THREAD

**Issue by 42degrees** [lbryio/chainquery#49]
Why is the schema missing any reference to channels?  Seems like there should not only be some reference to channel name on the Claim, there should probably be a channels table to store all the known channels.

**Comment by tiger5226** [comment]
Thanks for looking into Chainquery! In this case Chainquery aligns with our [protobuf metadata schema](https://github.com/lbryio/lbry.tech/blob/master/documents/resources/schema.md). Everything in the blockchain is a claim. There are different types of claims. Currently we have 2, content claims and channel claims. To differentiate between claims there is a column `claim_type` which is an integer. A content claim is 1, and a channel claim is 2. In the future the schema can be extended add more types of claims. An example for searching claims would be:

https://chainquery.lbry.io/api/sql?query=SELECT%20name%20FROM%20claim%20WHERE%20claim_type=2%20LIMIT%20100

```SQL
SELECT name FROM claim WHERE claim_type=2 LIMIT 100
```

We have discussed adding another table just for channel claims for ease of use. There has not been much demand, and many of the queries we use currently work just as good with the claims table. Do you have an example where a query would benefit from have a separate table? Ease of use is a perfectly good reason too though. That has been the main reasoning thus far in our discussions. Also always happy to hear how it is being used, as there are many use cases I have not even thought of yet.

**Comment by tiger5226** [comment]
closing for now. Please reopen if you disagree.
