### ISSUE TITLE
Claim showing expired but not in the app

### ISSUE THREAD

**Issue by tiger5226** [lbryio/chainquery#55]
https://chainquery.lbry.io/api/sql?query=SELECT%20*%20FROM%20claim%20WHERE%20name%20=%22open-source-video-editing-lesson-4%22

Chainquery has it as expired which is why it would not show up in the search results, but it is does link properly in the app. We need to check how it ended up in that if it is wrong. Also check if lbrycrd agrees.

**Comment by tiger5226** [comment]
created from https://github.com/lbryio/lighthouse/issues/120

**Comment by shyba** [comment]
here is another one: https://chainquery.lbry.io/api/sql?query=SELECT%20*%20from%20claim%20where%20transaction_hash_id%20=%20%22f7a4fca549779d7f7e95a3c128235523f9fc50b7ec76d93ab0e5b35cbcb779f1%22;

it resolves fine as "rick-and-morty-evil-morty-theme-song#64dde445a114a723e7360472ece6e75958a3a173"

there are some more here:
https://chainquery.lbry.io/api/sql?query=select%20*%20from%20claim%20where%20bid_state%20=%20%22Expired%22%20order%20by%20height%20desc%20limit%2010;

**Comment by tiger5226** [comment]
This was related to this fix 037ca9dd24bf61aaa2d9217616f0acb66d2dddf2
