### ISSUE TITLE
supports not taken into account for effective amount / bid state

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/chainquery#60]
@skhameneh recently ran into an issue with the wrong CryptoCandor channel resolving on spee.ch using chainquery. It looks like we don't take supports into account - her channel was taken over at some point, I then added supports to it a few months ago. 9152f3b054f692076a6882d1b58a30e8781cc8e6 should be controlling. 

data:

id | name | author | bid_state | certificate | claim_address | claim_id | claim_type | content_type | created_at | description | effective_amount | fee | fee_address | fee_currency | height | is_filtered | is_nsfw | language | modified_at | publisher_id | publisher_sig | sd_hash | thumbnail_url | title | transaction_hash_id | transaction_time | valid_at_height | value_as_hex | value_as_json | version | vout
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
98468 | @CryptoCandor | Active | {"version":1,"keyType":3,"publicKey":"MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE4GkiCUZm5LR4HDM2YlYyhWaHpjMDL/5dfXx4a+ZVyEEIdqSF3+vOTEVQXhzvcnw7nMBbieCt4MaIVEyVIlhBNA=="} | bXsvpJvoJb9WYCaieFeAyZbQyb8PCuZ8Q1 | 9152f3b054f692076a6882d1b58a30e8781cc8e6 | 2 |   | 2018-04-21T11:23:49.000Z | 10000 | 0 |   |   | 290872 | FALSE | FALSE |   | 2018-09-17T17:45:32.000Z |   |   |   | ab4a154a651bf322d3bf473a033e32a2b275c6eecec553861dbfb45868de7f8b | 1.51E+09 | 290872 | 08011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004e06922094666e4b4781c3336625632856687a633032ffe5d7d7c786be655c8410876a485dfebce4c45505e1cef727c3b9cc05b89e0ade0c688544c9522584134 | {"Claim":{"version":"_0_0_1","claimType":"certificateType","certificate":{"version":"_0_0_1","keyType":"SECP256k1","publicKey":"MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE4GkiCUZm5LR4HDM2YlYyhWaHpjMDL/5dfXx4a+ZVyEEIdqSF3+vOTEVQXhzvcnw7nMBbieCt4MaIVEyVIlhBNA=="}}} | _0_0_1 | 0
260944 | @CryptoCandor | Controlling | {"version":1,"keyType":3,"publicKey":"MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE83RM8IIcAJe7oa6GglNLJCAMh8PhgjHA4Gsw8MZjLNp6XgwAXlD7sw4jS1e/zEsd+xfJ9AHVIEVoMgLUiYtZsQ=="} | bUtyuT8gs3xdBRarBZ3VD7Z9juBAsCfjbx | f3a6680f1c7e88f79759eb928185a2193d11e513 | 2 |   | 2018-08-19T19:45:13.000Z | 10000000 | 0 |   |   | 422675 | FALSE | FALSE |   | 2018-09-17T17:45:32.000Z |   |   |   | 5cb06452df7e0290393b91089881cbfab4fff46f0b57054e1de39635fe72d6f2 | 1.53E+09 | 426707 | 08011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004f3744cf0821c0097bba1ae8682534b24200c87c3e18231c0e06b30f0c6632cda7a5e0c005e50fbb30e234b57bfcc4b1dfb17c9f401d52045683202d4898b59b1 | {"Claim":{"version":"_0_0_1","claimType":"certificateType","certificate":{"version":"_0_0_1","keyType":"SECP256k1","publicKey":"MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE83RM8IIcAJe7oa6GglNLJCAMh8PhgjHA4Gsw8MZjLNp6XgwAXlD7sw4jS1e/zEsd+xfJ9AHVIEVoMgLUiYtZsQ=="}}} | _0_0_1 | 0

http://traction.lbry.io/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZV90YWJsZSI6Mjk4LCJmaWx0ZXIiOlsiQU5EIixbIj0iLFsiZmllbGQtaWQiLDczOTZdLCJAQ3J5cHRvQ2FuZG9yIl1dfSwidHlwZSI6InF1ZXJ5IiwiZGF0YWJhc2UiOjZ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=

**Comment by tiger5226** [comment]
I am going to make this a high priority issue. The bid_state is an important field.

**Comment by tiger5226** [comment]
So I took a look at this and Chainquery is using the `valid_at_height` to determine controlling state. The highest one is controlling. Below is the result Chainquery is getting from LBRYcrd:

```JSON
{
  "result": {
    "name": "@CryptoCandor",
    "value": "\b\u0001\u0010\u0002\"^\b\u0001\u0010\u0003\"X0V0\u0010\u0006\u0007*\u0086H\u00ce=\u0002\u0001\u0006\u0005+\u0081\u0004\u0000\n\u0003B\u0000\u0004\u00e0i\"\tFf\u00e4\u00b4x\u001c36bV2\u0085f\u0087\u00a63\u0003\/\u00fe]}|xk\u00e6U\u00c8A\bv\u00a4\u0085\u00df\u00eb\u00ceLEP^\u001c\u00efr|;\u009c\u00c0[\u0089\u00e0\u00ad\u00e0\u00c6\u0088TL\u0095\"XA4",
    "claimId": "9152f3b054f692076a6882d1b58a30e8781cc8e6",
    "txid": "ab4a154a651bf322d3bf473a033e32a2b275c6eecec553861dbfb45868de7f8b",
    "n": 0,
    "amount": 10000,
    "effective amount": 1000010000,
    "supports": [
      {
        "txid": "31ea9898b0ba99765afde3ff281503733fc38ff1dcd57aa5be4c382cc2e501df",
        "n": 0,
        "height": 438308,
        "valid at height": 438670,
        "amount": 1000000000
      }
    ],
    "height": 290872,
    "valid at height": 290872
  },
  "error": null,
  "id": "curltest"
}
```

Obviously, the other has a much higher `valid_at_height` hence its controlling state. I can switch this to effective amount instead and do a resync for `bid_state`. Are there any implications with doing this? I remember getting different results otherwise but I don't recall specifically. What about during takeovers, is the effective amount reflecting properly? 

I would also expect the valid height is for when a claim takes the controlling state. Why is it not getting updated again? @BrannonKing Should I create a LBRYcrd issue or do you expect this to never be updated again regardless of bid wars?

**Comment by tiger5226** [comment]
https://chainquery.lbry.io/api/sql?query=SELECT%20*%20FROM%20claim%20WHERE%20name%20=%22@CryptoCandor%22
