### ISSUE TITLE
Normalization Hardfork - Changes required

### ISSUE THREAD

**Issue by tiger5226** [lbryio/chainquery#67]
When the hardfork happens, Chainquery should also record the normalized name after a certain hight. 

See [here](https://github.com/lbryio/lbrycrd/issues/208)

**Comment by BrannonKing** [comment]
`getlcaimsforname` now (after norm release) returns the original name in a field called 'name' and the normalized name in a column called 'normalized_name'. `getclaimsintrie`'s name field is now `normalized_name`. There is a separate 'name' field for each claim returned there that contains the original name.

**Comment by tiger5226** [comment]
To support queries made against the name of a claim, we need to implement support for NFD normalization to store data in the database in that format so it can be properly compared. The `name` column will remain and new column called `normalized_name` will be added to the `claim` table. This will store the normalized claim name that can be used to query when comparisons are being made. 

Any user of Chainquery that would like to use the supported lbrycrd feature of normalized names will need to make sure they normalize their query parameters as NFD normalization is not supported by DBMS's. 

The current database will just perform a resync of the claims.

**Comment by tiger5226** [comment]
I spoke with @lyoshenka about this and we agreed on the following:

Research Results:

- lbrycrd is using ICU  v57.1 for normalization which supports UCA 8.0
- mysql v5.7 supports UCA 4.0 and 5.2
- mysql v.8.0 supports UCA 4.0, 5.2 and 9.0 
- NFD/NFC are formations(presentation) which will be provided by lbrycrd already.

Solution:

- Upgrade Chainquery DB to MySQL 8.0 to leverage UCA 9.0
- There are differences in support between UCA 8.0 and UCA 9.0 that could cause issues but we will cross that bridge when it comes. 

Summary:

The only way for lbrycrd and DBMS solutions to align on unicode would be for UCA 9.0. This would require @BrannonKing to upgrade the boost libraries for lbrycrd and to use ICU v58.2. This is not ideal and the extra work does not have good reasoning since we cannot predict any REAL issues with UCA support ( off by 1 version ). Keeping the changes to Chainquery will allow all other services to not have to make any changes. 

So I will create specific issues for the hardfork.
