### ISSUE TITLE
Release binaries directly and/or package as tar

### ISSUE THREAD

**Issue by kauffj** [lbryio/chainquery#70]
Per Lenny:

> the reason I ask for static paths in latest bins is because Dockerfiles support the ADD directive which will automagically grab an artifact be it a binary or an archive and then if it's an opensource archive format it will automagically unpack it without me having to go through the process in the container to install the proprietary unarchive software

**Comment by Leopere** [comment]
tar.gz is specifically in the Docker documentation.

**Comment by tiger5226** [comment]
Currently, with goreleaser, it does not support releasing archives in multiple formats. I have [created an issue](https://github.com/goreleaser/goreleaser/issues/902) to see if this is even possible as a feature request.

@nikooo777 - I know you wanted to keep zip releases. I also know lenny already has the workaround in place and working fine for now. So for right now, I say we keep it as is. If the goreleaser teams things this is a worthy feature, I might even be able to add it for them.

**Comment by Leopere** [comment]
Truthfully it's not the end of the world if we can't do tar.gz it just
makes containers cleaner that's all.  Tar.gz is also natively supported in
the linux kernel.

**Comment by tiger5226** [comment]
They decided to postpone it even longer. Closing issue.
