### ISSUE TITLE
e2e testing for chainquery

### ISSUE THREAD

**Issue by tiger5226** [lbryio/chainquery#77]
With the recent upgrade to SQLBoiler V3, I have found some issues. These issues would have been critical and are around the SQLBoiler upgrade. below is what we need to be able to always test:

- [x] We need chainquery to work with lbrycrd testnet 
- [x] We need to be able to supply lbrycrd with claims
- [ ] We need to be able to validate the correct of claimtrie actions in chainquery. ie - When I enter a claim all the values are as expected. When I update, overtake etc it shows in chainquery correctly. 
- [x] This should just be run in travis. 
- [x] @Leopere I think our travis jobs should just use docker so we can do this effectively. Thoughts?
- [ ] Common api actions should be validated with the tests as well. 
- [ ] Additional items to include are: Failed claims, reorg example, ( will add more as I think of them here ).

**Comment by Leopere** [comment]
I think that a good chunk of this could be done easily with Docker if not
the whole thing, the Chainquery build container could be next after our
work last night.

**Comment by tiger5226** [comment]
closing for now. The additional ones are nice to haves and will add more as needed.
