### ISSUE TITLE
effective amount/claim status issues with pending takeovers (publishes to existing names)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/chainquery#86]
I noticed an issue last week regarding claim updates/takeovers and effective amounts, and @shyba did some more digging to find additional cases. There's a bug currently in lbrycrd where the effective amount is set to 0 during a takeover bid. So the initial value will be 0 in the claim table. I've seen instances where this effective amount is shown correctly later (I believe this is when a takeover does happen), but the modified date is not updated. In other instances (see query below), the effective amount stays at 0. Not sure why there are so many in the accepted state, haven't dug into it yet. There also may be similar issues for non-takeovers, gotta explore more as well. 

Breakdown:
https://traction.lbry.io/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo2LCJ0eXBlIjoibmF0aXZlIiwibmF0aXZlIjp7InF1ZXJ5Ijoic2VsZWN0IGJpZF9zdGF0ZSwgY291bnQoKikgZnJvbSBjbGFpbSB3aGVyZSBlZmZlY3RpdmVfYW1vdW50ID0gMCBncm91cCBieSBiaWRfc3RhdGUiLCJ0ZW1wbGF0ZS10YWdzIjp7fX19LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=

Detailed:
https://traction.lbry.io/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo2LCJ0eXBlIjoibmF0aXZlIiwibmF0aXZlIjp7InF1ZXJ5Ijoic2VsZWN0IGJpZF9zdGF0ZSwgbmFtZSwgY2xhaW1faWQgZnJvbSBjbGFpbSB3aGVyZSBlZmZlY3RpdmVfYW1vdW50ID0gMCBncm91cCBieSBiaWRfc3RhdGUsIG5hbWUsIGNsYWltX2lkOyIsInRlbXBsYXRlLXRhZ3MiOnt9fX0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsidGFibGUuY29sdW1uX3dpZHRocyI6W251bGwsMzI4XX19

**Comment by tzarebczan** [comment]
Here's a good example where it's accepted/effective amount = 0 that wasn't updated:
https://traction.lbry.io/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6Mjk4LCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQtaWQiLDczOTZdLCJqZXJlbXkta2F1ZmZtYW4iXV19LCJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6Nn0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==

**Comment by tiger5226** [comment]
This is now resolved. When it was not ready to take over Chainquery was not reprocessing it later to set the correct effective amount and bid state. I have adjusted the query to also include those claims that have a validatheight that is greater than the height the last claim trie sync happened.
