### ISSUE TITLE
Handle double spent transactions

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/chainquery#93]
@akinwale found a scenario where double spent transactions are not handled properly - we show both. This will affect the explorer integration, but it's an existing explorer issue as well. 

The first tx with a low fee: https://explorer.lbry.io/tx/f3e0f653a8f7409940f804d89308b3f5c18c8749e929be1ef1f1bc9e4cec61ab

The double spend tx: https://explorer.lbry.io/tx/5943764d926c7b7faea01d1b575143606a012239dbf9cf21d8bfb7647f41f72a

https://traction.lbry.io/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MzA5LCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQtaWQiLDcyOTJdLCJmM2UwZjY1M2E4Zjc0MDk5NDBmODA0ZDg5MzA4YjNmNWMxOGM4NzQ5ZTkyOWJlMWVmMWYxYmM5ZTRjZWM2MWFiIiwiNTk0Mzc2NGQ5MjZjN2I3ZmFlYTAxZDFiNTc1MTQzNjA2YTAxMjIzOWRiZjljZjIxZDhiZmI3NjQ3ZjQxZjcyYSJdXX0sInR5cGUiOiJxdWVyeSIsImRhdGFiYXNlIjo2fSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319

**Comment by tiger5226** [comment]
The solution here is to cleanup old mempool transactions. Once the height is above what it was for we should remove those transactions.

**Comment by tiger5226** [comment]
This is now resolved. We clear the tx mempool of transactions that are no longer supposed to be there. So if they are not currently in the pool we remove those transactions. We do this by locking block processing for this state check.
