### ISSUE TITLE
Support  normalized name

### ISSUE THREAD

**Issue by tiger5226** [lbryio/chainquery#96]
- [ ] Added `normalized_name` column to the `claim` table. 
- [ ] Adjust the response for `getclaimsforname` to receive the new `normalized_name` field from the RPC response. 
- [ ] Adjust Claimtrie sync logic to set this field. 
- [ ] We will also need to rethink the claimtrie sync as well. Currently we get claims for what will be the vanity name. So we could be inefficiently syncing the claimtrie for no reason now if two names are normalized to be the same now.

**Comment by tiger5226** [comment]
The claimtrie sync needs to be changed because it will not grab the right claims that compete with one another once its all normalized. The query needs to group by `normalized_name` instead of `name`.

**Comment by BrannonKing** [comment]
to clarify, you don't actually use getclaimsintrie?

**Comment by BrannonKing** [comment]
and the getclaimsforname has an error in it; the new normalized_name field isn't actually the normalized name until after the hard-fork hits. I can make a change to that. Let me know what you want. I'm thinking to leave it as name until the fork and then call it normalized_name after the fork. That way you can detect the change by what data is there. (The individual claims will have the name field in them either way.)

**Comment by tiger5226** [comment]
>to clarify, you don't actually use getclaimsintrie? 

Correct. I do not use this RPC call. I use `getclaimsforname`. 

>and the getclaimsforname has an error in it; the new normalized_name field isn't actually the normalized name until after the hard-fork hits.

Is this an error or a feature? Either way, I was planning on doing full sync after the fork any way, so I don't think this is a problem for Chainquery as it will get updated either way after the fork. 

>I can make a change to that.

No I don't think anything is needed here.

**Comment by tiger5226** [comment]
solved with 1.7 release
