### ISSUE TITLE
Address missing from support/tip tx

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/chainquery#97]
https://explorer.lbry.io/tx/50aedf7eca5a4c99885658072553a1c4d10e3824be003fcd2ce2e592379341b8
![image](https://user-images.githubusercontent.com/8120721/52741775-2c8b9d00-2fa4-11e9-8fc4-baec4ac20a94.png)

**Comment by tzarebczan** [comment]
Spoke to @tiger5226 about this - it happens because the address list is blank on the outputs table for non-standard transactions (publishes/updates/supports/tips/). The solution is to post populate this data into the outputs table for these transactions. This should fix explorer and the claim address checking can even be simplified there. We should even be able to see a "view claim" hyperlink on tips/supports too.

**Comment by tiger5226** [comment]
solved with 6551528b59d62627f5ebc429a1661b281bef8bfb
